# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Have an apple.
email: thorson.daniel@gmail.com
description: Well it's gonna be pretty cool, probably.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://heybay.be" # the base hostname & protocol for your site
twitter_username: DanielThorson3
github_username: danthor1

# Build settings
markdown: kramdown
